### PR TITLE
Take relative directories into account

### LINKED ISSUE #8: Doesn't take `DW_AT_stmt_list` into account
I'm not entirely sure if `gimli`/`object` actually supports reading this, but not taking this into account produces wrong paths.

I will try and take a stab at this later.

### PR DESCRIPTION
**Pull request by daxpedda**
I think my original bug description in #8 is just plain wrong. This is the first time I look at DWARF, so I'm just piecing things together here.

The [DWARF 4 specification](https://dwarfstd.org/doc/DWARF4.pdf#[{%22num%22%3A365%2C%22gen%22%3A0}%2C{%22name%22%3A%22XYZ%22}%2C0%2C370%2Cnull]) says the following about `include_directories`:
> Each path entry is either a full path name or is relative to the current directory of the compilation.

In the DWARF 5 specification, I couldn't find any mention of `include_directories`, so I guess Rust produces invalid DWARF 5, but I believe the new field is called [`directories`](https://dwarfstd.org/doc/DWARF5.pdf#section.6.2):
> The first entry is the current directory of the compilation. Each additional path entry is either a full path name or is relative to the current directory of the compilation.

So the fix here is to apply the directory of the compilation when encountering relative paths.

Fixes #8.

### CODE REVIEW

File: wasm2map/src/lib.rs [hunk 1]
```diff
@@ -155,9 +155,17 @@ impl WASM {
                         // The directory index 0 is defined to correspond to the compilation unit directory.
                         if file.directory_index() != 0 {
```
Comment (daxpedda) [inline wasm2map/src/lib.rs:156]: I think we should remove this if check. WDYT?

Comment (mtolmacs) [reply wasm2map/src/lib.rs:156]: I agree, this can be removed.

**Comment by mtolmacs** [comment]
LGTM. Can you provide a test case covering this branch in the code?

File: wasm2map/src/lib.rs (hunk 1 above)
Comment (daxpedda) [reply wasm2map/src/lib.rs]: Done.

File: wasm2map/src/test.rs [hunk 2]
```diff
@@ -24,6 +24,21 @@ fn can_create_sourcemap() {
...
+            let sourcemap = mapper.map_v3();
+
+            // Any fixed relative path should have at least a `/` beforehand.
+            assert!(sourcemap.contains("/library/core/src/any.rs"));
+            assert!(sourcemap.contains("/library/core/src/panicking.rs"));
+        } else {
+            unreachable!()
+        }
+    });
+}
```
Comment (daxpedda) [inline wasm2map/src/test.rs:40]: I'm happy to take any suggestions on how to test this otherwise.

Comment (mtolmacs) [reply wasm2map/src/test.rs:40]: I think it's okay for now, the code path you added runs during the tests, and PR #10 will be the more significant one.

**Review by mtolmacs — APPROVED** [review]
Looks good! Thanks for your patience.
